#!/bin/bash

sxhkd &

if [ -x $HOME/.config/bspwm/dual_mode ]; then
	$HOME/.config/bspwm/./dual_mode
fi

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP2 -d 0

bspc config pointer_mod         mod4
bspc config pointer_action1     move

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a code-oss    				  desktop='^2' state=tiled	  follow=on
bspc rule -a firefox    				  desktop='^3' state=tiled    follow=on
bspc rule -a Zathura     		    	  desktop='^4' state=tiled	  follow=on
bspc rule -a calibre    	      		  desktop='^5'
bspc rule -a Gimp        	        	  desktop='^7' state=floating follow=on
bspc rule -a "microsoft teams - preview"  desktop='^8' state=tiled	  follow=on
bspc rule -a TelegramDesktop			  desktop='^10'

bspc rule -a Matplotlib  		   					   state=floating
bspc rule -a feh		  		   					   state=floating
bspc rule -a Electron    		   					   state=floating
bspc rule -a gksqt       		   					   state=floating
bspc rule -a "GNU Octave"    			 			   state=floating
bspc rule -a processing-app-Base    	 			   state=floating

$HOME/.config/polybar/launch.sh
